name: mlenv
channels:
  - nvidia
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - conda==23.5.2
  - setuptools
  - pip
  - wheel
  - conda-content-trust
  - conda-libmamba-solver
  - pytorch
  - torchaudio
  - torchvision
  - pytorch-cuda=11.8
